name: Hidden Tests

on:
  workflow_call:
    inputs:
      # The repository name: ${{ github.repository }}
      repository:
        required: true
        type: string
      # Run C/C++ tests
      cutest:
        default: false
        required: false
        type: boolean
      # Run python tests
      pytest:
        default: false
        required: false
        type: boolean
    secrets:
      # Token to access solutions repository
      token:
        required: false

jobs:
  cutest:
    if: ${{ inputs.cutest }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout src repository
      uses: actions/checkout@v4
      with:
        path: 'src'
        repository: '${{ inputs.repository }}'
        submodules: 'true'

    - name: Checkout solutions repository
      uses: actions/checkout@v4
      with:
        path: 'sol'
        repository: 'UBCSailbot/software-quiz-sample-solution'
        token: ${{ secrets.token }}

    - name: Copy solutions to src
      run: cp sol/c-cpp/test_standard_calc.cpp src/c-cpp

    - name: Build src with solutions with Make
      run: make -C src/c-cpp

    - name: Test src with solutions with CuTest
      run: src/c-cpp/test_standard_calc.o > /dev/null 2>&1

  pytest:
    if: ${{ inputs.pytest }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout src repository
      uses: actions/checkout@v4
      with:
        path: 'src'
        repository: '${{ inputs.repository }}'
        submodules: 'true'

    - name: Checkout solutions repository
      uses: actions/checkout@v4
      with:
        path: 'sol'
        repository: 'UBCSailbot/software-quiz-sample-solution'
        token: ${{ secrets.token }}

    - name: Copy solutions to src
      run: cp sol/python/test_standard_calc.py src/python

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies with Pip
      run: |
        python -m pip install --upgrade pip
        pip install pytest

    - name: Test src with solutions with Pytest
      run: |
        pytest src > /dev/null 2>&1
